apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-demo-cm
  namespace: demo
data:
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update

    # Enabling H2 Console
    spring.h2.console.enabled=true
    # Custom H2 Console URL
    spring.h2.console.path=/h2

    logging.level.root=info

    # Exposing no actuator endpoints except loggers, if enabled
    management.endpoints.web.exposure.include=loggers

    # Normally all endpoints except shutdown are enabled by default
    management.endpoints.enabled-by-default=false

    # Specifically enable loggers endpoint
    management.endpoint.loggers.enabled=true

    # Specify profile
    spring.profiles.active=dev
