apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-role
  namespace: pwn-me
rules:
- apiGroups:
  - ""
  resourceNames:
  - vulnerable-app
  resources:
  - "pods/exec"
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - vulnerable-app
  resources:
  - "pods"
  verbs:
  - get
