apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-app
  namespace: pwn-me
spec:
  restartPolicy: Always
  serviceAccountName: vulnerable-app
  containers:
  - image: alpine:latest
    imagePullPolicy: IfNotPresent
    name: vulnerable-app
    args:
    - sh
    - -c
    - "sleep inf"
